### ISSUE TITLE
CTFtime.org as team authentication source

### ISSUE THREAD

**Issue by kyprizel** [ctftime/ctftime.org#2]
Managing team names and aliases, creating teams after the CTF, merging existing teams - it's a routine process, but it takes a lot of time. What if we use CTFtime as an authentication source during event registration.

Personally, I don't like the idea of turning CTFtime to an OAUTH provider, so, may be we can issue per-user (per-team?) auth token and save them in event registration info, then automatically merge team by auth token, not just by team names?

**Comment by psifertex** [comment]
It'd have to be generated per-event too to prevent replay. And at that point, it seems like oath might actually be less hassle. I agree some organizers won't want to do that though, so not sure if some combination or some other approach is the way to go.

**Comment by kyprizel** [comment]
May be oauth idea isn't that bad, just need to be sure that CTFtime will not be single point of failure on huge events.

**Comment by gynvael** [comment]
To ask the hard question - is it worth it?

TBH, there aren't a lot of merges once you have 3 aliases:
- the main name
- the main name without spaces
- a max 5 character long version of the name
(e.g. having these 3 we didn't have to do a single merge in the whole season 2014, and we did play most of the CTFs)

The only problems this would actually solve is the sometimes occurring issue of a random person registering the name of a given team in a given event - I remember both us and PPP running into this from time to time last season, though in all cases it was solved by contacting the organizers and reclaiming the name.
Though this would only work in case the event fully relies on CTFTime.org for auth. Otherwise, a person might still register a team he is not a part of, but it would be easier to reclaim the name.

In my personal opinion: it's a "nice to have", but nothing really critical. That being said, I have no idea how many merges did kyprizel have to process by hand last year due to problems described above ;)

**Comment by kyprizel** [comment]
I did a lot, but team merging isn't a problem (I automated it), more interesting is per-player stats and other analytics.

**Comment by psifertex** [comment]
The main problem it solves isn't for the teams, but for the data importing process of organizers and ctftime admins. It means the data can be more granular (as kyprizel mentioned), but also updated more quickly and be more accurate. Heck, even now I've got a bug where our GitS database replaced spaces with underscores and we have to fix it to make the integration work correctly. 

It allows more automation of things.

**Comment by kyprizel** [comment]
It took just 8 years to implement OAuth.
