### ISSUE TITLE
Possible to attend a CTF event as an observer?

### ISSUE THREAD

**Issue by windowshopr** [ctftime/ctftime.org#251]
Hey! 

I just came across your website in my searches. I’m brand new to red teaming as a hobby, and I was wondering, is it possible to attend/“observe” a CTF event without being on a team? Would like to see how it works and maybe gain some experience! 

I tried submitting this using the non-organizer form but when I hit submit it says I was acting as a spammer, which I am not! Lol 

Thanks!!

**Comment by sourcekris** [comment]
I would just join the Discord servers for the CTFs and sign up so that you can at least read the challenge clues.

People will be on those discords early to look for keen people to join their teams. You can always have a chat to see if any of those folks want to have you along and observing them.

And for what its worth, hundreds of people play CTFs solo and do quite well. A team is not mandatory.

**Comment by windowshopr** [comment]
Thank you for the great info! I’ll check it out!
