### ISSUE TITLE
Event tasks and writeups

### ISSUE THREAD

**Issue by kyprizel** [ctftime/ctftime.org#5]
To collect writeups we need per event tasks information. Most of the CTF organizers don't add it to CTFtime (and I understand them).

Should we allow users (not organizers) to add tasks information by theirself?

May be we should drop this feature and send people to http://github.com/ctfs/ ?

**Comment by psifertex** [comment]
The github model works well for this task. If you don't just link to the github page, you could model the same process behind it -- anyone can submit questions, but they have to be approved. Could always automatically make the organizers mods and then have a few extra site wide mods too so the load is distributed. 

That said, there's nothing wrong with letting the existing write up repository just take over that function instead.

**Comment by kyprizel** [comment]
Now only organizers can manage tasks info. We can change the process so anyonce can add and edit tasks, but event organizers can delete info and "freeze" it so noone can edit it after the freeze.

The main idea of tasks/writeups at CTFtime was - let new people get some information on tasks and solving process, not sure if it works now.

**Comment by psifertex** [comment]
Yeah, given that, I would just let the write ups go elsewhere. There's no reason to have the information duplicated anyway. I'd vote for just removing it and focusing on other features then. 

It's nicer if all the write ups are together anyway, and github is really easy to mirror from so there's no worries someone is going to make a mistake and lose the whole archive. 

At most, maybe you could coordinate with the admin behind the write ups repo to allow some easy process for the proper links to the event to be created in as automated a manner as possible.

**Comment by withzombies** [comment]
I think the current model is pretty good. It would be nice if people could submit their own write ups to it. 

I think the real problem is the interface needs work. For example, to find a contest-specific write-up, you need to click through 5 pages:

Ghost in the Shellcode 2014 - https://ctftime.org/event/118
Ghost in the Shellcode 2014  Tasks - https://ctftime.org/event/118/tasks/
Radioactive - https://ctftime.org/task/944
Radioactive by Hackney Style - https://ctftime.org/writeup/1080
The actual write-up - https://github.com/ctfs/write-ups-2014/tree/master/ghost-in-the-shellcode-2014/radioactive

**Comment by kyprizel** [comment]
withzombies, if you signed on than there are only 4 steps :) but you right - it's easy to improve, just need to add some search field with suggestions.

**Comment by kyprizel** [comment]
I changed the logic - now anyone can add and edit tasks, but event organizer can disable editing for existing tasks (for example, for that which they added).

**Comment by kyprizel** [comment]
I think that will be enought for a while - let's see what it gives to us.
